[package]
name = "rtt-target"
description = "Target side implementation of the RTT (Real-Time Transfer) I/O protocol"
version = "0.3.0"
edition = "2018"
readme = "../README.md"
keywords = ["no-std", "embedded", "debugging", "rtt"]
license = "MIT"
authors = ["Matti Virkkunen <mvirkkunen@gmail.com>"]
repository = "https://github.com/mvirkkunen/rtt-target"

[dependencies]
ufmt-write = "0.1.0"

# Platform specific stuff
cortex-m = { version = "0.7.2", optional = true }
riscv = { version = "0.6.0", optional = true }

# Dependencies used only for examples
[dev-dependencies]
ufmt = "0.1.0"
cortex-m-rt = "0.6.13"
panic-halt = "0.2.0"

[[example]]
name = "cortex-m-custom"
required-features = ["cortex-m"]

[[example]]
name = "cortex-m-print"
required-features = ["cortex-m"]

[[example]]
name = "cortex-m-ufmt"
required-features = ["cortex-m"]

# This is for the examples
[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"

[package.metadata.docs.rs]
features = ["cortex-m"]
